version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT.dkr.ecr.$REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - TAG_NAME=`date +"%Y%m%d%I%M%S"`
      - docker build -t $IMAGE_REPO_NAME:$TAG_NAME .
      - docker tag $IMAGE_REPO_NAME:$TAG_NAME $ACCOUNT.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:$TAG_NAME
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ACCOUNT.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:$TAG_NAME